### ISSUE TITLE
get rid of GSON dependency

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-set-owned-by-participant#1]
_GSON_ is specified as a mandatory dependency. However, it is never used as of now and I don't see a use case for doing so as the scope of this participant is very narrow.

Action: Get rid of the gson dependency

**Comment by LadyTsukiko** [comment]
Has been solved in [v1.1.1](https://github.com/jazz-community/rtc-set-owned-by-participant/releases/tag/v1.1.1).
